/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char123ProjectChar125RouteImport } from './routes/{-$project}'

const Char123ProjectChar125Route = Char123ProjectChar125RouteImport.update({
  id: '/{-$project}',
  path: '/{-$project}',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/{-$project}': typeof Char123ProjectChar125Route
}
export interface FileRoutesByTo {
  '/{-$project}': typeof Char123ProjectChar125Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/{-$project}': typeof Char123ProjectChar125Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/{-$project}'
  fileRoutesByTo: FileRoutesByTo
  to: '/{-$project}'
  id: '__root__' | '/{-$project}'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Char123ProjectChar125Route: typeof Char123ProjectChar125Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/{-$project}': {
      id: '/{-$project}'
      path: '/{-$project}'
      fullPath: '/{-$project}'
      preLoaderRoute: typeof Char123ProjectChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  Char123ProjectChar125Route: Char123ProjectChar125Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
